package com.yang.crm.settings.mapper;

import com.yang.crm.settings.domain.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Mar 02 22:00:34 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Mar 02 22:00:34 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Mar 02 22:00:34 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Mar 02 22:00:34 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Mar 02 22:00:34 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Mar 02 22:00:34 CST 2022
     */
    int updateByPrimaryKey(User record);

    /**
     * 用户登录时通过用户输入信息从数据库中查询对应用户
     * @param map 前端传来用户输入的账号和密码
     * @return 查询到的对应用户
     */
    User selectUserByLoginActAndPwd(Map<String, Object> map);

    /**
     * 查询所有用户
     * @return 所有用户集合
     */
    List<User> selectAllUsers();

    /**
     * 新增用户
     * @param user 用户
     * @return 新增条数
     */
    int insertNewUser(User user);
}